config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'posts#index'

  resources :posts do
    resources :comments, :except => [:index, :show]
  end

  resources :users, only: [:index, :show, :edit, :update]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :comment_text, :presence => true

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :title, :presence => true
  validates :content, :presence => true
  validates :date, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment Successfuly Added"
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Comment Successfully Updated"
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post.id)
  end

private
  def comment_params
    params.require(:comment).permit(:comment_text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new(params[:post])
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post Successfully Added"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post Successfully Updated"
      redirect_to posts_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :date)
    end
end

app/controllers/users_controller.rb
# class UsersController < ApplicationController
#   before_filter :authenticate_user!, except: [:index, :show]
#
#   def index
#     @users = User.all
#   end
#
#   def show
#     @user = User.find(params[:id])
#   end
#
#   def edit
#     @user = User.find(params[:id])
#   end
#
#   def update
#     @user = User.find(params[:id])
#     unless @user == current_user
#       flash[:error] = "You cannot edit another user's profile!"
#       redirect_to user_path(@user)
#     else
#       if @user.update(user_params)
#         flash[:notice] = "Profile updated."
#         redirect_to user_path(@user)
#       else
#         flash[:error] = "Profile not updated!"
#         redirect_to edit_user_path(@user)
#       end
#     end
#   end
#
#   private
#   def user_params
#     params.require(:user).permit(:name, :bio)
#   end
#
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :comment_text, 'Comment Text' %>
  <%= f.text_field :comment_text %>
  <%= f.submit class: "btn btn-sm btn-warning" %>
<% end %>

app/views/comments/edit.html.erb
<h2> Edit a Comment </h2>

<%= render 'form' %>

app/views/comments/new.html.erb
<div class="container">
  <div class="col-md-12">
    <h4>Enter Blog Comment</h4>
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class = "container">

    <nav class="navbar navbar-default" role="navigation">
      <ul class="nav navbar-nav navbar-left">
        <li id="nav-header"><%= link_to "Home", posts_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar pull-right">
        <% if user_signed_in? %>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li> <%= link_to "Sign up", new_user_registration_path %> </li>
        <li> <%= link_to "Sign in", new_user_session_path %> </li>
        <% end %>
      </ul>
    </nav>

    <% if user_signed_in? %>
    <p class="right-align">Logged in as <%= current_user.email %></p>
    <% end %>

    <%= flash[:notice] %>
    <%= flash[:alert] %>

    <%= yield %>

  </div>

</body>
</html>

app/views/posts/_form.html.erb
<div class="row">
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :date %>
  <%= f.text_field :date %>
  <%= f.submit class: "btn btn-sm btn-warning" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class= "container">
<h2>Edit Post</h2>

<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <% if @posts.any? %>
    <h3>Blog Posts:</h3>

<ul class="hidden-ul">
  <% @posts.each do |post| %>
    <h4><li> <%= link_to post.title, post_path(post.id) %> | <%= post.date %> </li></h4>
    <% end %>
  </ul>

  <% else %>
  <h4> Click the button below to begin </h4>
  <% end %>

<%= link_to "Add a Post", new_post_path, class: "btn btn-med btn-warning" %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="col-md-12">
    <h4>Enter Blog Post</h4>

    <% if @post.errors.any? %>
      <h4>There was an error creating your blog post, try again.</h4>
      <ul class="hidden-ul">
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
      </ul>
      <% end %>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">

  <div class="col-md-12">
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>
  <div class="col-md-12">

    <h3>Comments</h3>
    <ul>
      <% if @post.comments.any? %>

        <% @post.comments.each do |comment| %>
            <li><%= comment.comment_text %></li>
            <%= link_to "Edit", edit_post_comment_path(comment.post_id, comment.id) %> |
            <%= link_to "Delete", post_comment_path(comment.post_id, comment.id),
                                  :data => {:confirm => "Delete this comment?",
                                            :method => "delete"} %>
    <br>
        <% end %>
      <% end %>
    </ul>
    <hr>

  <%= link_to "Add a Comment", new_post_comment_path(@post), class: "btn btn-sm btn-warning" %>

  <hr>

  | <%= link_to "Home", posts_path, :class => "btn btn-sm btn-primary" %>
  | <%= link_to "Edit", edit_post_path,
                              :class => "btn btn-sm btn-primary" %>
  | <%= link_to "Delete", post_path(@post), class: "btn btn-sm btn-primary",
                              :data => { :confirm => "Delete this blog post?",
                                      :method => "delete"} %>
  |
</div>

app/views/users/index.html.erb
<!-- <% @users.each do |user| %>
<li><%= link_to user.email, user_path(user) %></li>
<% end %> -->

app/views/users/show.html.erb
<!-- <h1><%= @user.email %>'s Activity</h1>

<% if @user == current_user %>
<%= link_to "Edit Profile", edit_user_path(@user) %> |
<%= link_to "Edit Account", edit_user_registration_path(@user) %>
<% end %>

<% if @user.posts.any? %>
<h3>My Posts</h3>
<ul>
  <% @user.posts.each do |listing| %>
  <li>
    <%= link_to post.title, post_path(post) %>
    <% if @user == current_user %>
    <%= link_to 'Delete', post_path(post),
    :data => {
      :confirm => "You sure?",
      :method => "delete" },
      class: 'btn btn-xs btn-warning'
        %>
        <% end %>


      </li>
      <% end %>
    </ul>
    <% end %> -->